### ISSUE TITLE
How to create an operator in a non-default namespace

### ISSUE THREAD

**Issue by AllenZMC** [spotahome/redis-operator#157]
I get an error when I create an opertaor in another namespace(redis11)
```
time="2019-05-13T06:28:55Z" level=error msg="Error received: error creating crd redisfailovers.databases.spotahome.com: customresourcedefinitions.apiextensions.k8s.io is forbidden: User \"system:serviceaccount:redis11:redisoperator\" cannot create resource \"customresourcedefinitions\" in API group \"apiextensions.k8s.io\" at the cluster scope, exiting..." src="main.go:124"
```

**Comment by sergey-shambir** [comment]
We've faced with the same problem on our stage environment which had been turned off two weeks ago and was turned on today.

There are two reasons of this failure:
* Custom Resource Definition was renamed recently: https://github.com/spotahome/redis-operator/commit/26fe759cb5bdfa085b96821392da1ddd894577f4 - it's now `databases.spotahome.com/v1`, not `storage.spotahome.com/v1alpha2`
* The helm values.yaml (at path `redis-operator/charts/redisoperator/values.yaml`) has `tag: latest` by default


Looks like redis-operator pod on your cluster was restarted and pulled new docker image, but redis-operator was deployed with helm before 7.05.2019 (with old template).

I've used `kubectl -n redis-operator describe pod redisfailover-redisoperator-xxxxx` and there was docker pull event:

```
Normal  Pulled     13m   kubelet, worker-1  Successfully pulled image "quay.io/spotahome/redis-operator:latest"
```

So a lot of users who used default docker image tag in `values.yaml` will have problems (even on production environments) when their redis-operator pod will restart.

@jchanam can we stop this somehow, e.g. rollback docker image to the old version and change docker image name for redis-operator 1.0-rc?

@AllenZMC you have two options:
- re-deploy redis-operator with helm and update RedisFailover definition to use `apiVersion: databases.spotahome.com/v1` instead of `apiVersion: storage.spotahome.com/v1alpha2`, than re-deploy your RedisFailover resource
- or just rollback redis-operator, i.e. re-deploy it with fixed docker image tag - i suggest `tag: 0.5.8`

**Comment by sergey-shambir** [comment]
@jchanam at least there must be fixed tag in `values.yaml`, which is updated with release scripts or manually. I suggest to introduce fixed major version for both docker tag and tag value in `values.yaml`

**Comment by nicholasklem** [comment]
I used the deployment file `all-redis-operator-resources.yaml` and stumbled on the `namespace: default` of the `ClusterRoleBinding`, which is a required field. I deployed the operator to namespace`redis` and got this error untill I understood why.

**Comment by zedtux** [comment]
Would be great to be able to deploy in a different namespace.

Could someone from SpotAHome tell us if this could be included in a future release please?

**Comment by seafoodbuffet** [comment]
Maybe I'm missing something but I managed the deploy the operator to a custom namespace by updating the operator deployment yaml, like below. The operator itself is now running in the `redis` namespace and I'm able to spin up RedisFailover resources in other namespaces

```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: redisoperator
  name: redisoperator
  namespace: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redisoperator
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: redisoperator
      namespace: redis
    spec:
      serviceAccountName: redisoperator
      containers:
        - image: quay.io/spotahome/redis-operator:latest
          imagePullPolicy: IfNotPresent
          name: app
          securityContext:
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 1000
          resources:
            limits:
              cpu: 100m
              memory: 50Mi
            requests:
              cpu: 10m
              memory: 50Mi
      restartPolicy: Always
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: redisoperator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: redisoperator
subjects:
  - kind: ServiceAccount
    name: redisoperator
    namespace: redis
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: redisoperator
rules:
  - apiGroups:
      - databases.spotahome.com
    resources:
      - redisfailovers
    verbs:
      - "*"
  - apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
    verbs:
      - "*"
  - apiGroups:
      - ""
    resources:
      - pods
      - services
      - endpoints
      - events
      - configmaps
    verbs:
      - "*"
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - "get"
  - apiGroups:
      - apps
    resources:
      - deployments
      - statefulsets
    verbs:
      - "*"
  - apiGroups:
      - policy
    resources:
      - poddisruptionbudgets
    verbs:
      - "*"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: redisoperator
  namespace: redis
```

**Comment by phlegx** [comment]
@seafoodbuffet 

Interesting that this did work for you. I tried your exact yaml, exchanging only the namespace, but still get this error when I deploy the operator:

```
time="2021-02-26T09:14:23Z" level=info msg="Listening on :9710 for metrics exposure" src="asm_amd64.s:1337"

time="2021-02-26T09:14:23Z" level=warning msg="controller name not provided, it should have a name, fallback name to: *redisfailover.RedisFailoverHandler" controller=redisfailover operator=redis-operator src="generic.go:64"

time="2021-02-26T09:14:23Z" level=info msg="starting operator" operator=redis-operator src="main.go:87"

time="2021-02-26T09:14:23Z" level=error msg="Error received: error creating crd redisfailovers.databases.spotahome.com: customresourcedefinitions.apiextensions.k8s.io is forbidden: User \"system:serviceaccount:redis-operator:default\" cannot create resource \"customresourcedefinitions\" in API group \"apiextensions.k8s.io\" at the cluster scope, exiting..." src="main.go:124"

time="2021-02-26T09:14:23Z" level=info msg="Stopping everything, waiting 5s..." src="main.go:101"

error executing: error creating crd redisfailovers.databases.spotahome.com: customresourcedefinitions.apiextensions.k8s.io is forbidden: User "system:serviceaccount:redis-operator:default" cannot create resource "customresourcedefinitions" in API group "apiextensions.k8s.io" at the cluster scope
```

Any ideas what can be done to resolve this issue?
